package product

// запрос на создание таблицы товаров заказа
const sqlCreateProducts = `
CREATE TABLE IF NOT EXIST products (
	id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	order_id bigint NOT NULL,
	description varchar NOT NULL,
	price double precision NOT NULL,
	CONSTRAINT product_order_key FOREIGN KEY (order_id) REFERENCES orders (id)
);
`

// запрос на создание товара
// $1 - идентификатор заказа, к которому принадлежит товар
// $2 - наименование товара
// $3 - цена товара
const sqlAddProduct = `
INSERT INTO products VALUES(DEFAULT, $1, $2, $3);
`

// запрос на поиск товаров по номеру заказа
// $1 - номер заказа
const sqlFindOrderProducts = `
SELECT p.* FROM products p JOIN orders o ON o.id = p.order_id WHERE p.order_id = $1;
`
