package user

// sqlCreateTable - запрос на создание таблицы пользователей
const sqlCreateTable = `
ADD TABLE IF NOT EXIST users (
	id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	login varchar NOT NULL UNIQUE,
	password varchar NOT NULL
);
`

// sqlFindByID - запрос на поиск пользователя по идентификатору
// $1 - идентификатор пользователя
const sqlFindByID = "SELECT * FROM users WHERE id = $1;"

// sqlFindByID - запрос на поиск пользователя по login
// $1 - login пользователя
const sqlFindByLogin = "SELECT * FROM users WHERE login = $1;"

const sqlAdd = `
INSERT INTO users VALUES(DEFAULT, $1, $2) RETURNING *;
`
